import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/shared/Navbar";

import ToastProvider from "@/providers/toast.provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Donation app",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true} className={inter.className}>
        <ToastProvider>
          <Navbar></Navbar>
          {children}
        </ToastProvider>
      </body>
    </html>
  );
}
